### ISSUE TITLE
fillEmptyMeasuresWithWholeRest option not working

### ISSUE THREAD

**Issue by mjy9088** [opensheetmusicdisplay/opensheetmusicdisplay#1339]
# Error log

```log
index.js:762 Error rendering sheet: TypeError: Cannot read properties of undefined (reading 'addGraphicalNoteToNoteMap')
StackTrace: 
TypeError: Cannot read properties of undefined (reading 'addGraphicalNoteToNoteMap')
    at new GraphicalNote (GraphicalNote.ts:31:20)
    at new VexFlowGraphicalNote (VexFlowGraphicalNote.ts:21:9)
    at VexFlowGraphicalSymbolFactory.createNote (VexFlowGraphicalSymbolFactory.ts:124:16)
    at VexFlowMusicSheetCalculator.createGraphicalMeasure (MusicSheetCalculator.ts:2616:89)
    at VexFlowMusicSheetCalculator.createGraphicalMeasuresForSourceMeasure (MusicSheetCalculator.ts:2429:52)
    at VexFlowMusicSheetCalculator.prepareGraphicalMusicSheet (MusicSheetCalculator.ts:167:64)
    at VexFlowMusicSheetCalculator.initialize (MusicSheetCalculator.ts:122:14)
    at new GraphicalMusicSheet (GraphicalMusicSheet.ts:40:25)
    at OpenSheetMusicDisplay.updateGraphic (OpenSheetMusicDisplay.ts:185:24)
    at OpenSheetMusicDisplay.load (OpenSheetMusicDisplay.ts:175:14)
```

# How to reproduce

add option `fillEmptyMeasuresWithWholeRest: 1`, load musicxml with empty measure

# Problematic Code

[passing undefined](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/MusicSheetCalculator.ts#L2620) always lead `read properties of undefined` error.

**Comment by sschmidTU** [comment]
I don't get that error with an empty measure, can you add the musicxml sample that causes this?

my sample: (score of one empty measure)
[empty_measure.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10865110/empty_measure.zip)

**Comment by mjy9088** [comment]
Sorry I meant empty measure without rest. [this file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10869903/empty_measure.musicxml.zip) should reproduce the error.

[to_reproduce.patch](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10869918/to_reproduce.patch)

**Comment by sschmidTU** [comment]
Fixed.

<img width="84" alt="image" src="https://user-images.githubusercontent.com/33069673/227316628-ef016334-3d36-45d1-95c3-33e46c0e9e55.png">

`osmd.EngravingRules.FillEmptyMeasuresWithWholeRest = 1`

This was a surprisingly interesting issue, because this can only happen if it's the first measure in the piece and no voice has been created yet in the staff, in which case we also can't know which id the voice will have in future (unless we look ahead).
But it should basically only happen for a case like this of a single empty measure.
