### ISSUE TITLE
Lyrics Bugs Since Expressions

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#330]
It seems like some bugs crept in with the recent develop commits.
Of course we can discuss this tomorrow, just wanted to share some material already.

In Schubert - An die Musik, the lyrics are misplaced and reaching beyond the measure:
![image](https://user-images.githubusercontent.com/33069673/44363415-692e7e00-a4c4-11e8-8049-aa828f396150.png)

Mozart - Das Veilchen doesn't load:
<details>
  <summary>
    StackTrace
  </summary>
```
  | TypeError: notes[(index - 1)].getKeyProps is not a function at http://localhost:8000/demo.js:37051:45
  at Array.forEach (<anonymous>)at Function.AlignRestsToNotes (http://localhost:8000/demo.js:37033:13)

  at http://localhost:8000/demo.js:37107:26
  at Array.forEach (<anonymous>)
  at Formatter.alignRests (http://localhost:8000/demo.js:37106:14)
  at Formatter.format (http://localhost:8000/demo.js:37481:12)
  at VexFlowMeasure.vexflowMeasure.formatVoices (http://localhost:8000/demo.js:69526:35)
  at VexFlowMusicSheetCalculator../src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts.VexFlowMusicSheetCalculator.calculateMeasureXLayout (http://localhost:8000/demo.js:69531:36)
  at VexFlowMusicSheetCalculator../src/MusicalScore/Graphical/MusicSheetCalculator.ts.MusicSheetCalculator.calculateXLayout (http://localhost:8000/demo.js:62681:49)
-- | --
```
</details>

**Comment by sschmidTU** [comment]
And a minor issue that we need to think about anyways is collisions/spacing between lyrics and dynamics.
![image](https://user-images.githubusercontent.com/33069673/44363702-33d66000-a4c5-11e8-9af2-ca9235ce6119.png)
(Debussy - Mandoline)

**Comment by sschmidTU** [comment]
We should figure out which commits or which parts of the code cause this.

**Comment by sschmidTU** [comment]
Oh, and this (dynamics are cut off in OSMD Functions Test Expressions)
![image](https://user-images.githubusercontent.com/33069673/44364220-b14ea000-a4c6-11e8-9d99-1a3ba7da8411.png)

**Comment by bneumann** [comment]
My guess: all of them. We found some major issues with the bounding boxes that we fixed. But they have been worked around since the beginning so we need to clean up the rest of the code as well. For example the lyrics x alignment.

**Comment by matt-uib** [comment]
Yes let's have a look tomorrow on this. Could be becauses we finally have correct bounding boxes or that i added the options with alignRests=true to the formatter.format(), which was there in the wrong place, but used without any effect there.

**Comment by bneumann** [comment]
Oh and I found another bounding box just before calling it a day. Sometimes for a not yet known reason some measures don't have bounding boxes. Mostly the first ones in a system which might explained your Schubert issue
